### ISSUE TITLE
No module named 'twitter'

### ISSUE THREAD

**Issue by cookgroup9999** [JustinELRoberts/CookGroupBots#3]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/bot.py", line 606, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/cookgroup/BOT CG/CookGroupBots-master/cogs/twitterSuccessPoints.py", line 4, in <module>
    import twitter
ModuleNotFoundError: No module named 'twitter'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 385, in <module>
    bot.load_extension(f"cogs.{cog}")
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/bot.py", line 678, in load_extension
    self._load_from_module_spec(spec, name)
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/bot.py", line 609, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.twitterSuccessPoints' raised an error: ModuleNotFoundError: No module named 'twitter'

**Comment by johan-naizu** [comment]
`pip install twitter` 
i guess
